### PR TITLE
Michael branch

### PR DESCRIPTION
**Pull request by mir1995**
Tom, 

I have restored the datasets and uploaded the original raw data in case we need to verify the changes.

Also, during the reducing of the datasets there was an error in the assertion as United Kingdom in the Countries csv.file did not match UK in the capacity csv.file . For now I changed the original dataset to UK, but eventually I will code it.

### CODE REVIEW

**Comment by Batto1300** [comment]
Just to be sure, I still see the `datasets/correlation_el_capacity_latitude.py`, is that intended?

**Comment by mir1995** [comment]
now should be ok

On 10 Oct 2018, at 15:48, Tommaso Ricci <notifications@github.com<mailto:notifications@github.com>> wrote:


Just to be sure, I still see the datasets/correlation_el_capacity_latitude.py, is that intended?

**Comment by Batto1300** [comment]
Ok, I'm merging, next time it's better if we name the branch with a self-explaining name like `exploratory-analysis-latitude`

**Comment by mir1995** [comment]
Sounds good, so we create a branch for each task?


On 10 Oct 2018, at 15:53, Tommaso Ricci <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I'm merging, next time it's better if we name the branch with a self-explaining name like exploratory-analysis-latitude

**Comment by Batto1300** [comment]
Yep, every self-contained feature (exploratory analysis, prediction, data cleaning) must be a branch so that every branch is as independent as possible and we can track the progress of the project just by looking at the branches very easily.

**Pull request merged**
